"""shortURL table

Revision ID: df82355e7c0e
Revises: 
Create Date: 2019-11-30 17:17:57.729965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df82355e7c0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortURL',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=8), nullable=True),
    sa.Column('destination', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shortURL_identifier'), 'shortURL', ['identifier'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortURL_identifier'), table_name='shortURL')
    op.drop_table('shortURL')
    # ### end Alembic commands ###
